controller:
  kind: DaemonSet
  nodeSelector:
    workload-type: entrypoint
    kubernetes.io/os: linux
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"
  service:
    type: LoadBalancer
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: ultihash-test
      service.beta.kubernetes.io/aws-load-balancer-scheme: internal  # Use 'internet-facing' to provision a public NLB
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: 10254
      service.beta.kubernetes.io/aws-load-balancer-subnets: ${load_balancer_subnets}
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
