apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ultihash-testing
spec:
  amiFamily: Ubuntu
  role: ${node_registration_role}
  subnetSelectorTerms:
    - tags:
        Name: "ultihash-test-private-eu-central-1b"
  securityGroupSelectorTerms:
    - tags:
        Name: "ultihash-test-node"
  tags:
    created_by: karpenter
    purpose: ultihash-testing
  detailedMonitoring: false
  associatePublicIPAddress: false
  userData: |
    #!/bin/bash
    # Enable all tracing capabilities
    echo 0 > /proc/sys/kernel/yama/ptrace_scope
    # Mount the instance store
    sudo mkfs.ext4 /dev/nvme1n1
    sudo mount -t ext4 /dev/nvme1n1 /opt